services:
  - type: web
    name: semana14-daea-api
    runtime: docker
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
    plan: free
    autoDeploy: true
    healthCheckPath: /health