databases:
  - name: semana14-db
    databaseName: hangfire_db
    user: hangfire_user
    plan: free

services:
  - type: web
    name: semana14-daea-api
    runtime: docker
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: semana14-db
          property: connectionString
    plan: free
    autoDeploy: true
    healthCheckPath: /health